USE quote_system;
SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS ip_system_official_members (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  system_code VARCHAR(50) NOT NULL,
  jurisdiction_code VARCHAR(20) NOT NULL,
  name_zh VARCHAR(150) NOT NULL DEFAULT '',
  name_en VARCHAR(200) NOT NULL DEFAULT '',
  member_type VARCHAR(50) NOT NULL DEFAULT 'country',
  membership_relation_type VARCHAR(80) NOT NULL DEFAULT '',
  pct_route_type VARCHAR(80) NOT NULL DEFAULT '',
  regional_system_code VARCHAR(50) NOT NULL DEFAULT '',
  route_remark VARCHAR(1000) NOT NULL DEFAULT '',
  effective_date DATE NULL,
  source_name VARCHAR(150) NOT NULL DEFAULT '',
  source_url VARCHAR(500) NOT NULL DEFAULT '',
  remark VARCHAR(1000) NOT NULL DEFAULT '',
  internal_remark VARCHAR(1000) NOT NULL DEFAULT '',
  remark_updated_at DATETIME NULL,
  remark_updated_by VARCHAR(255) NOT NULL DEFAULT '',
  is_confirmed TINYINT(1) NOT NULL DEFAULT 1,
  display_order INT NOT NULL DEFAULT 1000,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_ip_system_official_member (system_code, jurisdiction_code),
  KEY idx_ip_system_official_members_system (system_code, is_confirmed, display_order),
  KEY idx_ip_system_official_members_code (jurisdiction_code, is_confirmed)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ip_system_official_members (
  system_code, jurisdiction_code, name_zh, name_en, member_type,
  effective_date, source_name, source_url, remark, is_confirmed, display_order
)
VALUES
  ('PCT', 'DE', '德国', 'Germany', 'country', '1978-01-24', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 10),
  ('PCT', 'JP', '日本', 'Japan', 'country', '1978-10-01', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 20),
  ('PCT', 'US', '美国', 'United States of America', 'country', '1978-01-24', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 30),
  ('PCT', 'CN', '中国', 'China', 'country', '1994-01-01', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 40),
  ('PCT', 'KR', '韩国', 'Republic of Korea', 'country', '1984-08-10', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 50),
  ('PCT', 'FR', '法国', 'France', 'country', '1978-02-25', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 60),
  ('PCT', 'GB', '英国', 'United Kingdom', 'country', '1978-01-24', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 70),
  ('PCT', 'IT', '意大利', 'Italy', 'country', '1985-03-28', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 80),
  ('PCT', 'ES', '西班牙', 'Spain', 'country', '1989-11-16', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 90),
  ('PCT', 'NL', '荷兰', 'Netherlands', 'country', '1979-07-10', 'WIPO PCT Contracting States', 'https://www.wipo.int/pct/en/pct_contracting_states.html', '', 1, 100),

  ('PARIS', 'DE', '德国', 'Germany', 'country', '1903-05-01', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 10),
  ('PARIS', 'JP', '日本', 'Japan', 'country', '1899-07-15', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 20),
  ('PARIS', 'US', '美国', 'United States of America', 'country', '1887-05-30', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 30),
  ('PARIS', 'CN', '中国', 'China', 'country', '1985-03-19', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 40),
  ('PARIS', 'KR', '韩国', 'Republic of Korea', 'country', '1980-05-04', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 50),
  ('PARIS', 'FR', '法国', 'France', 'country', '1884-07-07', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 60),
  ('PARIS', 'GB', '英国', 'United Kingdom', 'country', '1884-07-07', 'WIPO Lex Paris Convention Contracting Parties', 'https://www.wipo.int/wipolex/en/treaties/ShowResults?search_what=C&treaty_id=2', '', 1, 70),

  ('EPC', 'DE', '德国', 'Germany', 'country', '1977-10-07', 'EPO Member States', 'https://www.epo.org/en/about-us/foundation/member-states', '', 1, 10),
  ('EPC', 'FR', '法国', 'France', 'country', '1977-10-07', 'EPO Member States', 'https://www.epo.org/en/about-us/foundation/member-states', '', 1, 20),
  ('EPC', 'GB', '英国', 'United Kingdom', 'country', '1977-10-07', 'EPO Member States', 'https://www.epo.org/en/about-us/foundation/member-states', '', 1, 30),
  ('EPC', 'IT', '意大利', 'Italy', 'country', '1978-12-01', 'EPO Member States', 'https://www.epo.org/en/about-us/foundation/member-states', '', 1, 40),
  ('EPC', 'ES', '西班牙', 'Spain', 'country', '1986-10-01', 'EPO Member States', 'https://www.epo.org/en/about-us/foundation/member-states', '', 1, 50),
  ('EPC', 'NL', '荷兰', 'Netherlands', 'country', '1977-10-07', 'EPO Member States', 'https://www.epo.org/en/about-us/foundation/member-states', '', 1, 60),

  ('EU_DESIGN', 'AT', '奥地利', 'Austria', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 10),
  ('EU_DESIGN', 'BE', '比利时', 'Belgium', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 20),
  ('EU_DESIGN', 'BG', '保加利亚', 'Bulgaria', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 30),
  ('EU_DESIGN', 'HR', '克罗地亚', 'Croatia', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 40),
  ('EU_DESIGN', 'CY', '塞浦路斯', 'Cyprus', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 50),
  ('EU_DESIGN', 'CZ', '捷克', 'Czechia', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 60),
  ('EU_DESIGN', 'DK', '丹麦', 'Denmark', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 70),
  ('EU_DESIGN', 'EE', '爱沙尼亚', 'Estonia', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 80),
  ('EU_DESIGN', 'FI', '芬兰', 'Finland', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 90),
  ('EU_DESIGN', 'FR', '法国', 'France', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 100),
  ('EU_DESIGN', 'DE', '德国', 'Germany', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 110),
  ('EU_DESIGN', 'GR', '希腊', 'Greece', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 120),
  ('EU_DESIGN', 'HU', '匈牙利', 'Hungary', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 130),
  ('EU_DESIGN', 'IE', '爱尔兰', 'Ireland', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 140),
  ('EU_DESIGN', 'IT', '意大利', 'Italy', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 150),
  ('EU_DESIGN', 'LV', '拉脱维亚', 'Latvia', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 160),
  ('EU_DESIGN', 'LT', '立陶宛', 'Lithuania', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 170),
  ('EU_DESIGN', 'LU', '卢森堡', 'Luxembourg', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 180),
  ('EU_DESIGN', 'MT', '马耳他', 'Malta', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 190),
  ('EU_DESIGN', 'NL', '荷兰', 'Netherlands', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 200),
  ('EU_DESIGN', 'PL', '波兰', 'Poland', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 210),
  ('EU_DESIGN', 'PT', '葡萄牙', 'Portugal', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 220),
  ('EU_DESIGN', 'RO', '罗马尼亚', 'Romania', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 230),
  ('EU_DESIGN', 'SK', '斯洛伐克', 'Slovakia', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 240),
  ('EU_DESIGN', 'SI', '斯洛文尼亚', 'Slovenia', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 250),
  ('EU_DESIGN', 'ES', '西班牙', 'Spain', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 260),
  ('EU_DESIGN', 'SE', '瑞典', 'Sweden', 'country', NULL, 'EUIPO / European Union member countries', 'https://www.euipo.europa.eu/en/designs', '按欧盟成员资格适用；欧盟外观设计权利在欧盟成员国范围内适用。', 1, 270)
ON DUPLICATE KEY UPDATE
  name_zh = VALUES(name_zh),
  name_en = VALUES(name_en),
  member_type = VALUES(member_type),
  effective_date = VALUES(effective_date),
  source_name = VALUES(source_name),
  source_url = VALUES(source_url),
  remark = VALUES(remark),
  is_confirmed = VALUES(is_confirmed),
  display_order = VALUES(display_order);
