from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class FieldSourceMapping:
    field_name: str
    source_id: str
    source_name: str
    source_url: str
    source_version: str
    review_status: str = "pending_review"


FIELD_SOURCE_MATRIX: tuple[FieldSourceMapping, ...] = (
    FieldSourceMapping(
        "standard_code/display_code",
        "WIPO_ST3",
        "WIPO Standard ST.3",
        "https://www.wipo.int/standards/en/part_03_standards.html",
        "Current WIPO ST.3",
    ),
    FieldSourceMapping(
        "international_region",
        "UN_M49",
        "UNSD Standard Country or Area Codes for Statistical Use",
        "https://unstats.un.org/unsd/methodology/m49/",
        "Current online table",
    ),
    FieldSourceMapping(
        "business_region",
        "BUSINESS_REGION_SOURCE",
        "Internal business and market tag source",
        "internal://business-region-tags",
        "internal tag policy 2026-06",
    ),
    FieldSourceMapping(
        "default_office",
        "WIPO_IP_OFFICES_DIRECTORY",
        "WIPO Country Profiles - Directory of IP Offices",
        "https://www.wipo.int/en/web/country-profiles/directory-ip-offices",
        "WIPO Country Profiles - Directory of IP Offices current",
    ),
)

FIELD_SOURCE_IDS_BY_FIELD = {item.field_name: item.source_id for item in FIELD_SOURCE_MATRIX}

WIPO_LEX_CANDIDATE_SOURCE_NOTE = (
    "WIPO Lex 仅说明该对象进入候选池的来源，不作为地理区域、主管局或商务标签来源。"
)


UN_M49_REGION_BY_CODE: dict[str, str] = {
    **dict.fromkeys(
        [
            "AF",
            "AM",
            "AZ",
            "BD",
            "BN",
            "BT",
            "CN",
            "GE",
            "HK",
            "ID",
            "IN",
            "JP",
            "KG",
            "KH",
            "KP",
            "KR",
            "KZ",
            "LA",
            "LK",
            "MN",
            "MO",
            "MV",
            "MY",
            "NP",
            "PH",
            "PK",
            "SG",
            "TH",
            "TJ",
            "TM",
            "TW",
            "UZ",
            "VN",
        ],
        "Asia",
    ),
    **dict.fromkeys(["AE", "BH", "CY", "IL", "IQ", "IR", "JO", "KW", "LB", "OM", "QA", "SA", "SY", "TR", "YE"], "Middle East"),
    **dict.fromkeys(
        [
            "AD",
            "AL",
            "AT",
            "BA",
            "BE",
            "BG",
            "BY",
            "CH",
            "CZ",
            "DE",
            "DK",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "HR",
            "HU",
            "IE",
            "IS",
            "IT",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MD",
            "ME",
            "MK",
            "MT",
            "NL",
            "NO",
            "PL",
            "PT",
            "RO",
            "RS",
            "RU",
            "SE",
            "SI",
            "SK",
            "SM",
            "UA",
            "VA",
        ],
        "Europe",
    ),
    **dict.fromkeys(
        [
            "AO",
            "BF",
            "BI",
            "BJ",
            "BW",
            "CD",
            "CF",
            "CG",
            "CI",
            "CM",
            "CV",
            "DJ",
            "DZ",
            "EG",
            "ET",
            "GA",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GW",
            "KE",
            "KM",
            "LR",
            "LS",
            "LY",
            "MA",
            "MG",
            "ML",
            "MR",
            "MU",
            "MW",
            "MZ",
            "NA",
            "NE",
            "NG",
            "RW",
            "SC",
            "SD",
            "SL",
            "SN",
            "ST",
            "SZ",
            "TD",
            "TG",
            "TN",
            "TZ",
            "UG",
            "ZA",
            "ZM",
            "ZW",
        ],
        "Africa",
    ),
    **dict.fromkeys(["CA", "US"], "North America"),
    **dict.fromkeys(
        [
            "AG",
            "AR",
            "BB",
            "BO",
            "BR",
            "BS",
            "BZ",
            "CL",
            "CO",
            "CR",
            "CU",
            "DM",
            "DO",
            "EC",
            "GD",
            "GT",
            "GY",
            "HN",
            "HT",
            "JM",
            "KN",
            "LC",
            "MX",
            "NI",
            "PA",
            "PE",
            "PY",
            "SR",
            "SV",
            "TT",
            "UY",
            "VC",
            "VE",
        ],
        "Latin America and the Caribbean",
    ),
    **dict.fromkeys(["AU", "FJ", "KI", "NZ", "PG", "TO", "WS"], "Oceania"),
}


BUSINESS_TAGS_BY_CODE: dict[str, tuple[str, ...]] = {
    "CA": ("NORTH_AMERICA", "APEC"),
    "CO": ("LATIN_AMERICA",),
    "NL": ("EUROPE", "EU"),
}


WIPO_NATIONAL_OFFICE_ROWS: tuple[tuple[str, str, str, str], ...] = (
    ("AD", "Andorra", "default_receiving_office", "Trademarks Office of the Principality of Andorra Secretary of State of Tourism and Trade Ministry of Tourism and Trade"),
    ("AE", "United Arab Emirates", "default_receiving_office", "Innovation Development and Industrial Property Ministry of Economy"),
    ("AF", "Afghanistan", "default_receiving_office", "Afghanistan Central Business Registry & Intellectual Properties Ministry of Industry and Commerce"),
    ("AG", "Antigua and Barbuda", "default_receiving_office", "Antigua and Barbuda Intellectual Property & Commerce Office (ABIPCO) Ministry of Legal Affairs"),
    ("AL", "Albania", "default_receiving_office", "General Directorate of Industrial Property Ministry of Economy, Culture and Innovation"),
    ("AM", "Armenia", "default_receiving_office", "Intellectual Property Office Ministry of Economy of the Republic of Armenia"),
    ("AO", "Angola", "default_receiving_office", "Angolan Institute of Industrial Property Ministry of Industry"),
    ("AR", "Argentina", "default_receiving_office", "National Institute of Industrial Property"),
    ("AT", "Austria", "default_receiving_office", "Austrian Patent Office"),
    ("AU", "Australia", "default_receiving_office", "IP Australia"),
    ("AZ", "Azerbaijan", "default_receiving_office", "Intellectual Property Agency of the Republic of Azerbaijan"),
    ("BA", "Bosnia and Herzegovina", "default_receiving_office", "Institute for Intellectual Property of Bosnia and Herzegovina"),
    ("BB", "Barbados", "default_receiving_office", "Corporate Affairs and Intellectual Property Office Ministry of International Business and Industry"),
    ("BD", "Bangladesh", "default_receiving_office", "Department of Patents, Designs and Trademarks Ministry of Industries"),
    ("BE", "Belgium", "default_receiving_office", "The Belgian Intellectual Property Office"),
    ("BF", "Burkina Faso", "default_receiving_office", "National Center for Industrial Property Ministry of Industrial Development, Trade, Crafts and Small and Medium Enterprises"),
    ("BG", "Bulgaria", "default_receiving_office", "Patent Office of Republic of Bulgaria"),
    ("BH", "Bahrain", "default_receiving_office", "National Patent Office Directorate of Foreign Trade & Industrial Property Ministry of Industry and Commerce"),
    ("BI", "Burundi", "default_receiving_office", "Ministry of Commerce, Transport, Industry and Tourism General Directorate of Industry"),
    ("BJ", "Benin", "default_receiving_office", "Ministry of Industry and Trade"),
    ("BN", "Brunei Darussalam", "default_receiving_office", "Brunei Darussalam Intellectual Property Office Attorney General's Chambers"),
    ("BO", "Bolivia (Plurinational State of)", "default_receiving_office", "National Intellectual Property Service"),
    ("BR", "Brazil", "default_receiving_office", "National Institute of Industrial Property"),
    ("BS", "Bahamas", "default_receiving_office", "Registrar General's Department Intellectual Properties Section"),
    ("BT", "Bhutan", "default_receiving_office", "Department of Media Creative Industry and Industrial Property Ministry of Industry Commerce and Employment"),
    ("BW", "Botswana", "default_receiving_office", "Companies and Intellectual Property Authority Ministry of Trade and Entrepreneurship"),
    ("BY", "Belarus", "default_receiving_office", "National Center of Intellectual Property (NCIP)"),
    ("BZ", "Belize", "default_receiving_office", "Belize Intellectual Property Office"),
    ("CA", "Canada", "default_receiving_office", "Canadian Intellectual Property Office"),
    ("CD", "Democratic Republic of the Congo", "default_receiving_office", "Directorate of Industrial Property Secretariat for industry and small and medium enterprises (IPMEA) Ministry of Industry and SMEs"),
    ("CF", "Central African Republic", "default_receiving_office", "Direction de la propriete industrielle; Direction generale de l'industrie du developpement industriel Ministere de l'industrie, du commerce et des PMEs"),
    ("CG", "Congo", "default_receiving_office", "Directorate of the National Industrial Property Office Ministry of Industrial Development and Private Sector Promotion"),
    ("CH", "Switzerland", "default_receiving_office", "Swiss Federal Institute of Intellectual Property"),
    ("CI", "Cote d'Ivoire", "default_receiving_office", "Ivorian Office of Intellectual Property Ministry for Industry and the Promotion of the Private Sector"),
    ("CL", "Chile", "default_receiving_office", "National Institute of Industrial Property"),
    ("CM", "Cameroon", "default_receiving_office", "Directorate of Technological Development and Industrial Property Ministry of Mines, Industry and Technological Development"),
    ("CN", "China", "default_receiving_office", "China National Intellectual Property Administration"),
    ("CO", "Colombia", "default_receiving_office", "Superintendence of Industry and Commerce"),
    ("CR", "Costa Rica", "default_receiving_office", "Registro Nacional"),
    ("CU", "Cuba", "default_receiving_office", "Cuban Industrial Property Office Ministry of Science, Technology and Environment"),
    ("CV", "Cabo Verde", "default_receiving_office", "Institute for Quality Management and Intellectual Property"),
    ("CY", "Cyprus", "default_receiving_office", "Department of Registrar of Companies and Intellectual Property Ministry of Energy, Commerce and Industry"),
    ("CZ", "Czech Republic", "default_receiving_office", "Industrial Property Office of the Czech Republic"),
    ("DE", "Germany", "default_receiving_office", "German Patent and Trade Mark Office"),
    ("DK", "Denmark", "default_receiving_office", "Danish Patent and Trademark Office Ministry of Industry, Business and Financial Affairs"),
    ("DZ", "Algeria", "default_receiving_office", "Algerian National Institute of Industrial Property Ministry of Industry"),
    ("EC", "Ecuador", "default_receiving_office", "National Service of Intellectual Rights"),
    ("EE", "Estonia", "default_receiving_office", "The Estonian Patent Office"),
    ("EG", "Egypt", "default_receiving_office", "Egyptian Patent Office Academy of Scientific Research and Technology Ministry of Scientific Research"),
    ("ES", "Spain", "default_receiving_office", "Spanish Patent and Trademark Office"),
    ("FI", "Finland", "default_receiving_office", "Finnish Patent and Registration Office"),
    ("FR", "France", "default_receiving_office", "French Patent and Trademark Office"),
    ("GB", "United Kingdom", "default_receiving_office", "Intellectual Property Office"),
    ("GE", "Georgia", "default_receiving_office", "National Intellectual Property Center"),
    ("GR", "Greece", "default_receiving_office", "Hellenic Industrial Property Organization (OBI)"),
    ("GT", "Guatemala", "default_receiving_office", "Registry of Intellectual Property of Guatemala Ministry of Economy"),
    ("HN", "Honduras", "default_receiving_office", "Institute of Intellectual Property"),
    ("HR", "Croatia", "default_receiving_office", "State Intellectual Property Office of the Republic of Croatia (SIPO)"),
    ("HU", "Hungary", "default_receiving_office", "Hungarian Intellectual Property Office (HIPO)"),
    ("ID", "Indonesia", "default_receiving_office", "Directorate General of Intellectual Property Ministry of Law"),
    ("IE", "Ireland", "default_receiving_office", "Intellectual Property Office of Ireland (IPOI)"),
    ("IL", "Israel", "default_receiving_office", "Israel Patent Office Ministry of Justice"),
    ("IN", "India", "default_receiving_office", "Office of the Controller General of Patents, Designs and Trade Marks Department for Promotion of Industry and Internal Trade Ministry of Commerce and Industry"),
    ("IS", "Iceland", "default_receiving_office", "Icelandic Intellectual Property Office"),
    ("IT", "Italy", "default_receiving_office", "Markets and Consumers Protection Department Italian Patent and Trademark Office Ministry of enterprises and Made in Italy"),
    ("JM", "Jamaica", "default_receiving_office", "Jamaica Intellectual Property Office (JIPO)"),
    ("JP", "Japan", "default_receiving_office", "Japan Patent Office"),
    ("KE", "Kenya", "default_receiving_office", "Kenya Industrial Property Institute"),
    ("KH", "Cambodia", "default_receiving_office", "Department of Intellectual Property Ministry of Commerce"),
    ("KP", "Democratic People's Republic of Korea", "default_receiving_office", "Intellectual Property Administration (IPA) of the Democratic People's Republic of Korea"),
    ("KR", "Republic of Korea", "default_receiving_office", "Ministry of Intellectual Property"),
    ("KZ", "Kazakhstan", "default_receiving_office", "Committee of Intellectual Property Rights of the Ministry of Justice of the Republic of Kazakhstan"),
    ("LA", "Lao People's Democratic Republic", "default_receiving_office", "Department of Intellectual Property"),
    ("LB", "Lebanon", "default_receiving_office", "Office of Intellectual Property, Ministry of Economy and Trade"),
    ("LI", "Liechtenstein", "default_receiving_office", "Office of Economic Affairs Bureau of Intellectual Property"),
    ("LK", "Sri Lanka", "default_receiving_office", "National Intellectual Property Office of Sri Lanka"),
    ("LR", "Liberia", "default_receiving_office", "Liberia Intellectual Property Office"),
    ("LT", "Lithuania", "default_receiving_office", "State Patent Bureau of the Republic of Lithuania"),
    ("LU", "Luxembourg", "default_receiving_office", "Intellectual Property Office Ministry of the Economy"),
    ("LV", "Latvia", "default_receiving_office", "Patent Office of the Republic of Latvia"),
    ("MA", "Morocco", "default_receiving_office", "Moroccan Office of Industrial and Commercial Property"),
    ("MC", "Monaco", "default_receiving_office", "Intellectual Property Division Department of Economic Expansion"),
    ("MD", "Republic of Moldova", "default_receiving_office", "State Agency on Intellectual Property"),
    ("ME", "Montenegro", "default_receiving_office", "Directorate for Internal Market and Competition Ministry of Economic Development of Montenegro"),
    ("MG", "Madagascar", "default_receiving_office", "Malagasy Industrial Property Office Ministry of Industry, Trade and Craft"),
    ("MK", "North Macedonia", "default_receiving_office", "State Office of Industrial Property"),
    ("ML", "Mali", "default_receiving_office", "Malian Centre for the Promotion of Industrial Property (CEMAPI) Ministry of Trade and Industry"),
    ("MN", "Mongolia", "default_receiving_office", "Intellectual Property Office Implementing Agency of the Government of Mongolia"),
    ("MT", "Malta", "default_receiving_office", "Industrial Property Registrations Directorate Commerce Department Ministry for the Economy and Industry"),
    ("MU", "Mauritius", "default_receiving_office", "Industrial Property Office of Mauritius (IPOM) Ministry of Foreign Affairs, Regional Integration and International Trade"),
    ("MX", "Mexico", "default_receiving_office", "Mexican Institute of Industrial Property"),
    ("MY", "Malaysia", "default_receiving_office", "Intellectual Property Corporation of Malaysia"),
    ("MZ", "Mozambique", "default_receiving_office", "Industrial Property Institute Ministry of Industry and Commerce"),
    ("NA", "Namibia", "default_receiving_office", "Business and Intellectual Property Authority (BIPA) Ministry of Industrialization and Trade (MIT)"),
    ("NE", "Niger", "default_receiving_office", "National Agency for Industrial Property and Promotion of Innovation Ministry of Mines and Industrial Development"),
    ("NG", "Nigeria", "default_receiving_office", "Patents & Designs Office Commercial Law Department Federal Ministry of Industry, Trade & Investment,"),
    ("NI", "Nicaragua", "default_receiving_office", "Intellectual Property Registry Ministry of Development, Industry and Trade"),
    ("NL", "Netherlands", "default_receiving_office", "Netherlands Patent Office"),
    ("NO", "Norway", "default_receiving_office", "Norwegian Industrial Property Office"),
    ("NP", "Nepal", "default_receiving_office", "Department of Industries Department of Industry, Ministry of Industry, Commerce and Supplies"),
    ("NZ", "New Zealand", "default_receiving_office", "Intellectual Property Office of New Zealand (IPONZ)"),
    ("OM", "Oman", "default_receiving_office", "National Intellectual Property Office Ministry of Commerce, Industry and Investment Promotion"),
    ("PA", "Panama", "default_receiving_office", "Directorate General of the Industrial Property Registry Ministry of Commerce and Industries"),
    ("PE", "Peru", "default_receiving_office", "National Institute for the Defense of Competition and Protection of Intellectual Property"),
    ("PG", "Papua New Guinea", "default_receiving_office", "Intellectual Property Office of Papua New Guinea"),
    ("PH", "Philippines", "default_receiving_office", "Intellectual Property Office of the Philippines"),
    ("PK", "Pakistan", "default_receiving_office", "Patent Office Intellectual Property Organization of Pakistan (IPO-Pakistan)"),
    ("PL", "Poland", "default_receiving_office", "Patent Office of the Republic of Poland"),
    ("PT", "Portugal", "default_receiving_office", "Portuguese Institute of Industrial Property Ministry of Justice"),
    ("PY", "Paraguay", "default_receiving_office", "National Directorate of Intellectual Property"),
    ("RO", "Romania", "default_receiving_office", "State Office for Inventions and Trademarks"),
    ("RS", "Serbia", "default_receiving_office", "Intellectual Property Office of the Republic of Serbia"),
    ("RU", "Russian Federation", "default_receiving_office", "Federal Service for Intellectual Property"),
    ("SA", "Saudi Arabia", "default_receiving_office", "Saudi Authority for Intellectual Property (SAIP)"),
    ("SE", "Sweden", "default_receiving_office", "Swedish Intellectual Property Office (PRV)"),
    ("SG", "Singapore", "default_receiving_office", "Intellectual Property Office of Singapore (IPOS)"),
    ("SI", "Slovenia", "default_receiving_office", "Slovenian Intellectual Property Office (SIPO) Ministry of the Economy, Tourism and Sport"),
    ("SK", "Slovakia", "default_receiving_office", "Industrial Property Office of the Slovak Republic"),
    ("SM", "San Marino", "default_receiving_office", "Department for Economy State Office for Patents and Trademarks"),
    ("SN", "Senegal", "default_receiving_office", "Senegalese Agency for Industrial Property and Technological Innovation (ASPIT)"),
    ("SR", "Suriname", "default_receiving_office", "Intellectual Property Office of Suriname Ministry of Economic Affairs, Entrepreneurship and Technological Innovation"),
    ("SV", "El Salvador", "default_receiving_office", "Salvadoran Institute of Intellectual Property National Registry Center"),
    ("TH", "Thailand", "default_receiving_office", "Department of Intellectual Property (DIP) Ministry of Commerce"),
    ("TJ", "Tajikistan", "default_receiving_office", "National Center for Patents and Information Ministry of Economic Development and Trade of the Republic of Tajikistan"),
    ("TM", "Turkmenistan", "default_receiving_office", "State Service for Intellectual Property of Ministry of Finance and Economy of Turkmenistan"),
    ("TN", "Tunisia", "default_receiving_office", "National Institute for Standardization and Industrial Property"),
    ("TR", "Turkiye", "default_receiving_office", "Turkish Patent and Trademark Office"),
    ("TT", "Trinidad and Tobago", "default_receiving_office", "Intellectual Property Office - Ministry of Land and Legal Affairs"),
    ("TZ", "United Republic of Tanzania", "default_receiving_office", "Business Registrations and Licensing Agency (BRELA) Ministry of Industry and Trade"),
    ("UA", "Ukraine", "default_receiving_office", "National Intellectual Property Authority State Organization Ukrainian National Office for Intellectual Property and Innovations"),
    ("UG", "Uganda", "default_receiving_office", "Uganda Registration Services Bureau Ministry of Justice and Constitutional Affairs"),
    ("US", "United States of America", "default_receiving_office", "United States Patent and Trademark Office"),
    ("UY", "Uruguay", "default_receiving_office", "National Directorate of Industrial Property Ministry of Industry, Energy and Mining"),
    ("UZ", "Uzbekistan", "default_receiving_office", "Ministry of Justice of the Republic of Uzbekistan"),
    ("VC", "Saint Vincent and the Grenadines", "default_receiving_office", "Commerce and Intellectual Property Office"),
    ("VE", "Venezuela (Bolivarian Republic of)", "default_receiving_office", "Autonomous Service of Intellectual Property"),
    ("VN", "Viet Nam", "default_receiving_office", "Intellectual Property Office of Viet Nam Ministry of Science and Technology of Viet Nam"),
    ("WS", "Samoa", "default_receiving_office", "Registries of Companies and Intellectual Property Division (RCIP) Ministry of Commerce, Industry and Labour (MCIL)"),
    ("ZA", "South Africa", "default_receiving_office", "Companies and Intellectual Property Commission Department of Trade and Industry"),
    ("ZM", "Zambia", "default_receiving_office", "Patents and Companies Registration Agency Ministry of Commerce, Trade and Industry"),
    ("ZW", "Zimbabwe", "default_receiving_office", "Companies and Intellectual Property Office of Zimbabwe (CIPZ) Ministry of Justice, Legal and Parliamentary Affairs"),
    ("DJ", "Djibouti", "default_receiving_office", "Djiboutian Office of Industrial and Commercial Property"),
    ("DM", "Dominica", "default_receiving_office", "Companies and Intellectual Property Office Ministry of National Security and Home Affairs"),
    ("DO", "Dominican Republic", "default_receiving_office", "National Office of Industrial Property Ministry of Industry, Commerce and Mypimes"),
    ("ET", "Ethiopia", "default_receiving_office", "Ethiopian Intellectual Property Authority"),
    ("FJ", "Fiji", "default_receiving_office", "Office of the Attorney-General"),
    ("GA", "Gabon", "default_receiving_office", "Industrial Property Office Ministry of Industry and National Entrepreneurship"),
    ("GD", "Grenada", "default_receiving_office", "Corporate Affairs and Intellectual Property Office (CAIPO)"),
    ("GH", "Ghana", "default_receiving_office", "Registrar General's Department Ministry of Justice"),
    ("GM", "Gambia (the)", "default_receiving_office", "The Registrar General's Department Ministry of Justice"),
    ("GN", "Guinea", "default_receiving_office", "National Service of Industrial Property Ministry of Industry, SMEs and Promotion of the Private Sector"),
    ("GQ", "Equatorial Guinea", "default_receiving_office", "Scientific and Technological Research Council"),
    ("GW", "Guinea-Bissau", "default_receiving_office", "General Directorate of Industrial Property Ministry of Energy, Industry and Natural Resources"),
    ("GY", "Guyana", "default_receiving_office", "Deeds and Commercial Registries Ministry of Legal Affairs"),
    ("HT", "Haiti", "default_receiving_office", "Ministry of Trade and Industry"),
    ("IQ", "Iraq", "default_receiving_office", "Central Organization for Standardization and Quality Control Ministry of Planning"),
    ("IR", "Iran (Islamic Republic of)", "default_receiving_office", "Intellectual Property Center of the Islamic Republic of Iran"),
    ("JO", "Jordan", "default_receiving_office", "Industrial Property Protection Directorate Ministry of Industry, Trade and Supply"),
    ("KG", "Kyrgyzstan", "default_receiving_office", "Ministry of Science, Higher Education and Innovation of the Kyrgyz Republic"),
    ("KI", "Kiribati", "default_receiving_office", "Ministry of Commerce, Industry and Cooperatives"),
    ("KM", "Comoros", "default_receiving_office", "Comorian Intellectual Property Office Ministry of the Economy, Planning, Energy, Industry, Handicrafts, Tourism, Investments, Private Sector and Land Affairs"),
    ("KN", "Saint Kitts and Nevis", "default_receiving_office", "The Intellectual Property Office of St. Kitts and Nevis"),
    ("KW", "Kuwait", "default_receiving_office", "Ministry of Commerce and Industry Trademarks and Patents Department"),
    ("LC", "Saint Lucia", "default_receiving_office", "Registry of Companies and Intellectual Property"),
    ("LS", "Lesotho", "default_receiving_office", "Registrar General's Office (RGO) Ministry of Justice and Law"),
    ("LY", "Libya", "default_receiving_office", "Libyan authority for research Ministry of Higher Education and Scientific Research"),
    ("MR", "Mauritania", "default_receiving_office", "Directorate of Industry Ministry of Commerce, Industry, Handicraft and Tourism"),
    ("MV", "Maldives", "default_receiving_office", "Intellectual Property Unit Ministry of Economic Development"),
    ("MW", "Malawi", "default_receiving_office", "Department of Registrar General Ministry of Justice and Constitutional Affairs"),
    ("QA", "Qatar", "default_receiving_office", "Ministry of Commerce and Industry - State of Qatar Intellectual Property Protection Department"),
    ("RW", "Rwanda", "default_receiving_office", "Office of the Registrar General Rwanda Development Board"),
    ("SC", "Seychelles", "default_receiving_office", "Intellectual Property Office c/o The Registrar General's Office Registration Division Department of Legal Affairs President's Office"),
    ("SD", "Sudan", "default_receiving_office", "Registrar General of Intellectual Property Administration"),
    ("SL", "Sierra Leone", "default_receiving_office", "National Registry for Industrial Property and Copyright Office of the Administrator and Registrar General (OARG)"),
    ("ST", "Sao Tome and Principe", "default_receiving_office", "National Intellectual Property and Quality Service Secretary of State, Trade and Industry Ministry of Tourism, Culture, Commerce and Industry"),
    ("SY", "Syrian Arab Republic", "default_receiving_office", "Directorate of Industrial and Commercial Property Protection Ministry of Economy and Industry"),
    ("SZ", "Eswatini", "default_receiving_office", "Ministry of Commerce Industry and Trade Intellectual Property Office"),
    ("TD", "Chad", "default_receiving_office", "Ministry of Commerce and Industry"),
    ("TG", "Togo", "default_receiving_office", "National Institute for Industrial Property and Technology (INPIT)"),
    ("TO", "Tonga", "default_receiving_office", "Intellectual Property Office Ministry of Trade & Economic Development"),
    ("VA", "Holy See", "default_receiving_office", "Governorate of the Vatican City State"),
    ("YE", "Yemen", "default_receiving_office", "Ministry of Information, Culture & Tourism"),
)

OFFICE_DISPLAY_CODE_BY_COUNTRY: dict[str, str] = {
    "AU": "IP Australia",
    "CA": "CIPO",
    "CN": "CNIPA",
    "CO": "SIC",
    "DE": "DPMA",
    "JP": "JPO",
    "KR": "MOIP",
    "US": "USPTO",
}

OFFICE_NAME_CN_BY_COUNTRY: dict[str, str] = {
    "AU": "澳大利亚知识产权局",
    "CA": "加拿大知识产权局",
    "CN": "国家知识产权局",
    "CO": "哥伦比亚工业和商业监督局",
    "DE": "德国专利商标局",
    "JP": "日本特许厅",
    "KR": "韩国知识产权部",
    "NL": "荷兰专利局",
    "US": "美国专利商标局",
}

OFFICE_ALIASES_BY_COUNTRY: dict[str, tuple[str, ...]] = {
    "KR": ("KIPO", "Korean Intellectual Property Office", "韩国知识产权局"),
}
